# Generated by Django 5.0.6 on 2024-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=10)),
                ('taskDescription', models.CharField(max_length=10)),
                ('task_assign_date', models.DateField()),
                ('is_completed', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
